"use strict";
const C=BP_CONFIG,$=id=>document.getElementById(id),K="bp9_records",FID="bp9_file_id",FNAME="bp9_file_name",TK="bp9_theme";
let token="",expires=0,client=null,pickerReady=false,syncing=false;
const now=()=>new Date().toISOString(),uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random();
const load=()=>{try{return JSON.parse(localStorage.getItem(K)||"[]")}catch{return[]}},save=r=>localStorage.setItem(K,JSON.stringify(r));
const fileId=()=>localStorage.getItem(FID)||"",fileName=()=>localStorage.getItem(FNAME)||"";
function setFile(id,name){localStorage.setItem(FID,id);localStorage.setItem(FNAME,name||C.FILE_NAME);ui()}
function clearFile(){localStorage.removeItem(FID);localStorage.removeItem(FNAME);ui()}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function fmt(t){return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(t))}
function cls(s,d){if(s>=180||d>=120)return["bad","非常高","⚠️ 數值非常高；如有不適請立即就醫。"];if(s>=140||d>=90)return["warn","偏高","⚠️ 血壓偏高，建議休息後重測。"];if(s<90||d<60)return["warn","偏低","⚠️ 血壓偏低；如有不適請諮詢醫師。"];if(s>=130||d>=80)return["warn","稍高","ℹ️ 數值稍高，已完成紀錄。"];return["ok","一般範圍","✅ 紀錄已儲存。"]}
function driveMsg(m,bad=false){$("driveStatus").textContent=m;$("driveStatus").style.color=bad?"var(--danger)":""}
function ui(){let f=fileId();$("pick").disabled=!token||!pickerReady;$("create").disabled=!token;$("sync").disabled=!token||!f;$("forget").classList.toggle("hidden",!f);$("logout").classList.toggle("hidden",!token);$("fileBox").classList.toggle("hidden",!f);$("fileName").textContent=fileName()||C.FILE_NAME;$("fileId").textContent=f?"fileId: "+f:""}
function defaults(){let d=new Date(),l=new Date(d-d.getTimezoneOffset()*60000);$("date").value=l.toISOString().slice(0,10);$("time").value=l.toISOString().slice(11,16)}
function initGoogle(){if(!window.google?.accounts?.oauth2||!window.gapi){setTimeout(initGoogle,250);return}gapi.load("picker",{callback:()=>{pickerReady=true;ui()}});client=google.accounts.oauth2.initTokenClient({client_id:C.CLIENT_ID,scope:C.SCOPE,callback:()=>{},error_callback:e=>{let type=e?.type||"unknown";if(type==="popup_failed_to_open")driveMsg("Google 登入視窗無法開啟。請允許彈出式視窗，或先用 Safari/Chrome 開啟網站再登入。",true);else if(type==="popup_closed")driveMsg("Google 登入視窗已關閉，尚未完成授權。",true);else driveMsg("Google 登入發生錯誤："+type,true)}})}
function auth(interactive=true){return new Promise((res,rej)=>{if(token&&Date.now()<expires)return res(token);if(!client)return rej(Error("Google 元件尚未載入"));client.callback=r=>{if(r.error)return rej(Error(r.error_description||r.error));token=r.access_token;expires=Date.now()+(Number(r.expires_in||3600)-60)*1000;driveMsg("Google Drive 已登入。");ui();res(token)};client.requestAccessToken({prompt:interactive?"consent":""})})}
async function api(url,opt={}){let t=await auth(false),r=await fetch(url,{...opt,headers:{...(opt.headers||{}),Authorization:"Bearer "+t}});if(!r.ok){let m=await r.text();if(r.status===401){token="";expires=0;ui()}throw Error("Drive API "+r.status+": "+m)}return r}
function picker(){if(!token)return driveMsg("請先登入 Google。",true);let v=new google.picker.DocsView(google.picker.ViewId.DOCS).setMimeTypes("text/csv,text/plain,application/vnd.ms-excel").setIncludeFolders(false);new google.picker.PickerBuilder().setAppId(C.APP_ID).setOAuthToken(token).setDeveloperKey(C.API_KEY).addView(v).setTitle("選擇 BloodPressure.csv").setCallback(async d=>{if(d.action!==google.picker.Action.PICKED)return;let f=d.docs?.[0];if(!f)return;setFile(f.id,f.name);try{await syncDrive()}catch(e){syncError(e)}}).build().setVisible(true)}
function cell(v){v=String(v??"");return/[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function csv(records=load()){let a=[["record_id","timestamp_iso","updated_at_iso","deleted","日期","時間","收縮壓","舒張壓","心跳","備註"]];[...records].sort((x,y)=>new Date(x.time)-new Date(y.time)).forEach(r=>{let d=new Date(r.time);a.push([r.id,r.time,r.updatedAt||r.time,r.deleted?1:0,d.toLocaleDateString("zh-TW"),d.toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false}),r.sys,r.dia,r.hr,r.note||""])});return"\ufeff"+a.map(r=>r.map(cell).join(",")).join("\r\n")}
function parse(text){let lines=text.replace(/^\ufeff/,"").split(/\r?\n/).filter(Boolean),out=[];for(let line of lines.slice(1)){let c=[],x="",q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch=='"'&&line[i+1]=='"'){x+='"';i++}else if(ch=='"')q=!q;else if(ch==","&&!q){c.push(x);x=""}else x+=ch}c.push(x);if(c.length>=10&&c[0]&&!isNaN(Date.parse(c[1])))out.push({id:c[0],time:new Date(c[1]).toISOString(),updatedAt:!isNaN(Date.parse(c[2]))?new Date(c[2]).toISOString():c[1],deleted:c[3]=="1"||c[3]=="true",sys:+c[6],dia:+c[7],hr:+c[8],note:c[9]||""});else if(c.length>=5){let d=new Date(c[0]+" "+c[1]);if(!isNaN(d))out.push({id:uid(),time:d.toISOString(),updatedAt:now(),deleted:false,sys:+c[2],dia:+c[3],hr:+c[4],note:c.length>=7?c[6]||"":c[5]||""})}}return out.filter(r=>[r.sys,r.dia,r.hr].every(Number.isFinite))}
function merge(a,b){let m=new Map;[...b,...a].forEach(r=>{let e=m.get(r.id);if(!e||Date.parse(r.updatedAt||r.time)>=Date.parse(e.updatedAt||e.time))m.set(r.id,r)});return[...m.values()].sort((x,y)=>new Date(x.time)-new Date(y.time))}
async function createFile(){await auth(false);let boundary="bp9_"+Date.now(),meta={name:C.FILE_NAME,mimeType:"text/csv",description:"BloodPressure PWA V9 sync file",appProperties:{app:"BloodPressurePWA",version:"9"}},body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: text/csv; charset=UTF-8\r\n\r\n${csv()}\r\n--${boundary}--`;let r=await api("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name",{method:"POST",headers:{"Content-Type":"multipart/related; boundary="+boundary},body}),f=await r.json();setFile(f.id,f.name);await syncDrive()}
async function syncDrive(){if(syncing)return;let id=fileId();if(!id)return driveMsg("請先選擇或建立同步檔案。",true);syncing=true;ui();driveMsg("正在同步…");try{let r=await api(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`),remote=parse(await r.text()),all=merge(load(),remote);save(all);await api(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(id)}?uploadType=media`,{method:"PATCH",headers:{"Content-Type":"text/csv; charset=UTF-8"},body:csv(all)});render();driveMsg(`同步完成，共 ${all.filter(x=>!x.deleted).length} 筆。`)}finally{syncing=false;ui()}}
function syncError(e){console.error(e);let m=String(e.message||e);if(m.includes("404")){clearFile();driveMsg("找不到同步檔案，請重新選擇。",true)}else if(m.includes("401")){token="";expires=0;ui();driveMsg("授權已到期，請重新登入。",true)}else driveMsg("同步失敗："+m,true)}
async function auto(){if(!$("autoSync").checked||!fileId())return;if(!token||Date.now()>=expires)return driveMsg("已存本機；請重新登入後同步。",true);try{await syncDrive()}catch(e){syncError(e)}}
function active(){return load().filter(r=>!r.deleted)}
function render(){let all=active().sort((a,b)=>new Date(b.time)-new Date(a.time)),last=all[0],n=new Date();$("latest").textContent=last?`${last.sys}/${last.dia}`:"—";$("latestTime").textContent=last?fmt(last.time):"尚無紀錄";$("count").textContent=all.length;$("month").textContent=`本月 ${all.filter(r=>{let d=new Date(r.time);return d.getFullYear()==n.getFullYear()&&d.getMonth()==n.getMonth()}).length} 筆`;if(all.length){$("average").textContent=`${Math.round(all.reduce((s,r)=>s+r.sys,0)/all.length)}/${Math.round(all.reduce((s,r)=>s+r.dia,0)/all.length)}`;$("avgHr").textContent=`平均心跳 ${Math.round(all.reduce((s,r)=>s+r.hr,0)/all.length)}`;$("state").textContent=cls(last.sys,last.dia)[1]}else{$("average").textContent="—";$("avgHr").textContent="平均心跳 —";$("state").textContent="—"}let q=$("search").value.toLowerCase(),rows=[...all].sort((a,b)=>($("sort").value=="asc"?1:-1)*(new Date(a.time)-new Date(b.time))).filter(r=>!q||[fmt(r.time),r.sys,r.dia,r.hr,r.note].join(" ").toLowerCase().includes(q)),tb=$("history").querySelector("tbody");tb.innerHTML=rows.map(r=>{let c=cls(r.sys,r.dia);return`<tr><td>${fmt(r.time)}</td><td><b>${r.sys}/${r.dia}</b></td><td>${r.hr}</td><td><span class="pill ${c[0]}">${c[1]}</span></td><td>${esc(r.note)}</td><td><div class="row"><button data-e="${r.id}">編輯</button><button data-d="${r.id}" class="danger">刪除</button></div></td></tr>`}).join("");$("history").classList.toggle("hidden",!rows.length);$("empty").classList.toggle("hidden",!!rows.length);tb.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>edit(b.dataset.e));tb.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>del(b.dataset.d));draw(all.slice(0,+$("range").value).reverse());ui()}
function edit(id){let r=load().find(x=>x.id==id&&!x.deleted);if(!r)return;let d=new Date(r.time),l=new Date(d-d.getTimezoneOffset()*60000);$("editId").value=id;$("date").value=l.toISOString().slice(0,10);$("time").value=l.toISOString().slice(11,16);$("sys").value=r.sys;$("dia").value=r.dia;$("hr").value=r.hr;$("note").value=r.note;$("formTitle").textContent="編輯紀錄";$("save").textContent="更新紀錄";$("cancel").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
function cancel(){$("form").reset();$("editId").value="";$("formTitle").textContent="新增紀錄";$("save").textContent="儲存紀錄";$("cancel").classList.add("hidden");defaults()}
async function del(id){if(!confirm("確定刪除這筆紀錄？"))return;let r=load(),i=r.findIndex(x=>x.id==id);if(i<0)return;r[i]={...r[i],deleted:true,updatedAt:now()};save(r);render();await auto()}
function draw(r){let c=$("chart"),x=c.getContext("2d"),w=c.width,h=c.height,dark=document.documentElement.dataset.theme=="dark";x.clearRect(0,0,w,h);x.fillStyle=dark?"#0f1c2e":"#fff";x.fillRect(0,0,w,h);if(!r.length){x.fillStyle="#64748b";x.font="22px sans-serif";x.fillText("尚無資料",w/2-45,h/2);return}let p={l:48,r:16,t:20,b:35},max=Math.max(180,...r.flatMap(a=>[a.sys,a.dia,a.hr])),X=i=>p.l+(r.length==1?0:(w-p.l-p.r)*i/(r.length-1)),Y=v=>h-p.b-(v-40)*(h-p.t-p.b)/(max-40);[["sys","#2563eb",[]],["dia","#dc2626",[8,5]],["hr","#16a34a",[2,4]]].forEach(([k,col,dash])=>{x.beginPath();x.strokeStyle=col;x.lineWidth=2.7;x.setLineDash(dash);r.forEach((a,i)=>i?x.lineTo(X(i),Y(a[k])):x.moveTo(X(i),Y(a[k])));x.stroke();x.setLineDash([])})}
$("form").onsubmit=async e=>{e.preventDefault();let id=$("editId").value,t=new Date(`${$("date").value}T${$("time").value}:00`),r=load(),o={id:id||uid(),time:t.toISOString(),updatedAt:now(),deleted:false,sys:+$("sys").value,dia:+$("dia").value,hr:+$("hr").value,note:$("note").value.trim()},i=r.findIndex(x=>x.id==id);i>=0?r[i]=o:r.push(o);save(r);let c=cls(o.sys,o.dia);cancel();render();$("status").className="status "+c[0];$("status").textContent=c[2];await auto()};
$("login").onclick=async()=>{try{await auth(true);if(!fileId())$("first").showModal();else await syncDrive()}catch(e){driveMsg("登入失敗："+e.message,true)}};$("pick").onclick=picker;$("dPick").onclick=()=>{$("first").close();picker()};$("create").onclick=()=>createFile().catch(syncError);$("dCreate").onclick=()=>{$("first").close();$("create").click()};$("sync").onclick=()=>syncDrive().catch(syncError);$("forget").onclick=()=>{if(confirm("解除目前檔案綁定？檔案不會刪除。"))clearFile()};$("logout").onclick=()=>{if(token)google.accounts.oauth2.revoke(token);token="";expires=0;ui();driveMsg("已登出 Google。")};$("cancel").onclick=cancel;$("range").onchange=render;$("search").oninput=render;$("sort").onchange=render;document.querySelectorAll("[data-note]").forEach(b=>b.onclick=()=>$("note").value=b.dataset.note);
$("export").onclick=()=>{let b=new Blob([csv()],{type:"text/csv;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=C.FILE_NAME;a.click();URL.revokeObjectURL(u)};$("import").onchange=async e=>{let f=e.target.files[0];if(!f)return;let inc=parse(await f.text());save(merge(load(),inc));render();alert(`已匯入 ${inc.length} 筆`);e.target.value="";await auto()};$("clear").onclick=()=>{if(confirm("清除本機快取？Drive 檔案不會刪除。")){localStorage.removeItem(K);render()}};$("theme").onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme=="dark"?"light":"dark";localStorage.setItem(TK,document.documentElement.dataset.theme);render()};
document.documentElement.dataset.theme=localStorage.getItem(TK)||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");defaults();render();window.addEventListener("load",initGoogle);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
